-- ==================== PostgreSQL Primary Init ====================
-- This script initializes the primary server for streaming replication

-- Create replication user (for replica to connect)
CREATE USER replicator WITH REPLICATION ENCRYPTED PASSWORD 'replicator_password';

-- Grant connect permission to replication user
GRANT CONNECT ON DATABASE budget TO replicator;

-- ==================== Replication Configuration ====================
-- These are set via POSTGRES_INITDB_ARGS in docker-compose.yml:
-- -c max_wal_senders=10          (max concurrent replication connections)
-- -c max_replication_slots=10    (max replication slots)
-- -c wal_level=replica           (write-ahead log level for replication)
-- -c hot_standby=on              (allow queries on standby)

-- Configure postgresql.conf for replication (via pg_hba.conf equivalent)
-- The pg_hba.conf is auto-generated by Postgres, but we ensure replicator can connect

-- Optional: Create a replication slot (modern approach, better than recovery.conf)
-- SELECT * FROM pg_create_physical_replication_slot('standby_slot');

-- ==================== Application Database Setup ====================
-- The budget database and budget user are created by default via POSTGRES_DB and POSTGRES_USER
-- Ensure budget user has proper permissions:

GRANT USAGE ON SCHEMA public TO budget;
GRANT CREATE ON SCHEMA public TO budget;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO budget;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO budget;

-- ==================== Monitoring ====================
-- Create a monitoring user (optional, for health checks)
-- CREATE USER monitoring WITH PASSWORD 'monitoring_password';
-- ALTER USER monitoring CREATEDB CREATEROLE;
